// Mocks generated by Mockito 5.4.6 from annotations
// in cinemax/test/providers/person_detail_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cinemax/models/cast.dart' as _i5;
import 'package:cinemax/models/movie.dart' as _i2;
import 'package:cinemax/models/review.dart' as _i6;
import 'package:cinemax/models/video.dart' as _i7;
import 'package:cinemax/repos/movie_repo.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMovie_0 extends _i1.SmartFake implements _i2.Movie {
  _FakeMovie_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepo extends _i1.Mock implements _i3.MovieRepo {
  @override
  _i4.Future<List<_i2.Movie>> getTrending({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrending, [], {#page: page}),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> getPopular({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getPopular, [], {#page: page}),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> getTopRated({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRated, [], {#page: page}),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> getNowPlaying({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlaying, [], {#page: page}),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> getUpcoming({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcoming, [], {#page: page}),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<_i2.Movie> getMovieDetail(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [movieId]),
            returnValue: _i4.Future<_i2.Movie>.value(
              _FakeMovie_0(this, Invocation.method(#getMovieDetail, [movieId])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Movie>.value(
              _FakeMovie_0(this, Invocation.method(#getMovieDetail, [movieId])),
            ),
          )
          as _i4.Future<_i2.Movie>);

  @override
  _i4.Future<List<_i5.Cast>> getCredits(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getCredits, [movieId]),
            returnValue: _i4.Future<List<_i5.Cast>>.value(<_i5.Cast>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Cast>>.value(
              <_i5.Cast>[],
            ),
          )
          as _i4.Future<List<_i5.Cast>>);

  @override
  _i4.Future<List<_i6.Review>> getReviews(int? movieId, {int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getReviews, [movieId], {#page: page}),
            returnValue: _i4.Future<List<_i6.Review>>.value(<_i6.Review>[]),
            returnValueForMissingStub: _i4.Future<List<_i6.Review>>.value(
              <_i6.Review>[],
            ),
          )
          as _i4.Future<List<_i6.Review>>);

  @override
  _i4.Future<List<_i7.Video>> getVideos(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideos, [movieId]),
            returnValue: _i4.Future<List<_i7.Video>>.value(<_i7.Video>[]),
            returnValueForMissingStub: _i4.Future<List<_i7.Video>>.value(
              <_i7.Video>[],
            ),
          )
          as _i4.Future<List<_i7.Video>>);

  @override
  _i4.Future<List<_i2.Movie>> getSimilar(int? movieId, {int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getSimilar, [movieId], {#page: page}),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<List<_i2.Movie>> discoverByGenre(int? genreId, {int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#discoverByGenre, [genreId], {#page: page}),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);

  @override
  _i4.Future<Map<String, dynamic>> getPersonDetail(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonDetail, [personId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.Movie>> getPersonMovieCredits(int? personId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonMovieCredits, [personId]),
            returnValue: _i4.Future<List<_i2.Movie>>.value(<_i2.Movie>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Movie>>.value(
              <_i2.Movie>[],
            ),
          )
          as _i4.Future<List<_i2.Movie>>);
}
